config/routes.rb
AwesomePages::Application.routes.draw do

  root to: 'pages#index'

  get '/add',     to: 'pages#new',     as: :add_root_page
  get '*id/add',  to: 'pages#new',     as: :add_new_page
  get '*id/edit', to: 'pages#edit',    as: :edit_page
  get '*id',      to: 'pages#show',    as: :show_page

  post '/pages',  to: 'pages#create',  as: :create_page
  put '*id',      to: 'pages#update',  as: :update_page
  delete '*id',   to: 'pages#destroy', as: :delete_page
end

app/models/page.rb
class Page < ActiveRecord::Base
  include Russian

  attr_accessible :name, :title, :description

  has_ancestry orphan_strategy: :destroy

  RUSSIAN_SYMBOLS = 'А-яЁё'

  before_validation :generate_slug

  validates :name, :slug, uniqueness: true, presence: true
  validates_format_of :name, with: /\A[a-zA-Z0-9_#{RUSSIAN_SYMBOLS}]+\z/

  def to_param
    slug
  end

  def generate_slug
    return if name.blank?

    translited_name = Russian::transliterate(name)
    self.slug = translited_name.parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include PagesHelper

  before_filter :ensure_root_page_exists, only:   [:index]
  before_filter :ensure_to_add_root_page, only:   [:new]
  before_filter :load_root_page,          only:   [:index]
  before_filter :load_resource,           except: [:index, :create]
  before_filter :load_parent,             only:   [:create], if: ->{ first_page.present? }

  def index
  end

  def show
  end

  def new
    parent = @page
    @page = Page.new
    @page.parent = parent
  end

  def create
    @page = Page.new(params[:page])
    @page.parent_id = @parent.present? ? @parent.id : nil

    if @page.save
      redirect_to nested_page_path(@page), notice: I18n.t('pages.create')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @page.update_attributes(params[:page])
      redirect_to nested_page_path(@page), notice: I18n.t('pages.update')
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to root_path, notice: I18n.t('pages.delete')
  end

  private

  def ensure_root_page_exists
    redirect_to add_root_page_path unless first_page.present?
  end

  def ensure_to_add_root_page
    if params[:id].nil? && first_page.present?
      redirect_to root_path
    end
  end

  def load_resource
    return unless first_page.present?

    @page = page_by_slug(params[:id])
    return @page if @page.present?

    redirect_to root_path, flash: { error: I18n.t('errors.pages.not_found') }
  end

  def load_parent
    @parent = page_by_slug(params[:page][:parent_slug])

    return @parent if @parent.present?

    redirect_to root_path, flash: { error: I18n.t('errors.pages.without_parent') }
  end

  def load_root_page
    @page ||= first_page.present? ? first_page.root : nil
  end

  def first_page
    @first_page ||= Page.first
  end

  def page_by_slug(slug)
    Page.find_by_slug(slug_out_of(slug))
  end

  def slug_out_of(url)
    return nil if url.nil?

    sliced_url = url.split('/') - ['add', 'edit']
    sliced_url.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def nested_page_path(page)
    '/' + (page.ancestors + [page]).map(&:to_param).join('/')
  end

  def slug_of(page)
    page.present? ? page.slug : ''
  end

  def parse_description_of(page)
    regexp = /\*\*(.*)\*\*|\\\\(.*)\\\\|\(\((.+)\s(([a-z0-9_]+\/?[^\/])*)\)\)/

    page.description.gsub(regexp) do |string|
      case string
      when /\*\*(.*)\*\*/
        "<b>#{$1}</b>"
      when /\\\\(.*)\\\\/
        "<i>#{$1}</i>"
      when /\(\((.+)\s(([a-z0-9_]+\/?[^\/])*)\)\)/
        "<a href='#{request.protocol}#{request.host_with_port}/#{$2}'>#{$1}</a>"
      end
    end
  end
end

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.haml
!!!
%html
  %head
    %title AwesomePages
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

  %body
    #messages= render 'layouts/messages'
    .wrapper-content
      = yield

app/views/pages/_collection.haml
- if page.children.any?
  %ul
    - page.children.each do |page|
      %li
        = link_to page.title, show_page_path(page)
        = render 'collection', page: page

app/views/pages/_form.haml
= simple_form_for page, url: url do |f|
  = f.input :name
  = f.input :title
  = f.input :description, as: :text
  = f.hidden_field :parent_slug, value: slug_of(page.parent)
  = f.submit 'Save'

app/views/pages/_page.haml
%h2= page.title

%p= parse_description_of(page).html_safe

.action-buttons
  = link_to 'Add new page', add_new_page_path(page)
  = link_to 'Edit page', edit_page_path(page)
  = link_to 'Delete page', delete_page_path(page), method: :delete

%span Subpages
- if page.children.any?
  = render 'collection', page: page
- else
  %span There is no subpages yet.

app/views/pages/edit.haml
%h1 Update the page
= link_to 'Back to show', nested_page_path(@page)
= render 'form', page: @page, url: update_page_path(@page)

app/views/pages/index.haml
%h1 Root page
= render 'page', page: @page

app/views/pages/new.haml
%h1 Create a new page
= link_to 'Back to show', nested_page_path(@page)
= render 'form', page: @page, url: create_page_path

app/views/pages/show.haml
%h1 Show page
= link_to 'Root page', root_path
= render 'page', page: @page